#!/bin/bash

SYMLINKS=**/*.symlink
TEMPLATES=**/*.template

for f in $SYMLINKS
do
  filename=$(basename $f)
  dest="$HOME/.${filename%.*}"
  target="$PWD/$f"
  echo "Installing $dest"
  ln -sfn $target $dest
done

for f in $TEMPLATES
do
  filename=$(basename $f)
  dest="$HOME/.${filename%.*}"
  target="$PWD/$f"
  echo "Installing $dest"
  cp -i $target $dest ||:
done
