#!/usr/bin/env bash

mkdir -p ~/.config

for f in $(find . -name "*.symlink")
do
  target=$PWD/${f#./}
  filename=${f#./*/}
  dest=$HOME/${filename%.*}
  echo "Installing $dest"
  ln -sfn $target $dest
done

for f in $(find . -name "*.dot_template")
do
  target=$PWD/${f#./}
  filename=${f#./*/}
  dest=$HOME/${filename%.*}
  echo "Installing $dest"
  cp -i $target $dest ||:
done
