#!/usr/bin/env bash

for f in $(find . -name "*.symlink")
do
  filename=${f#./*/}
  dest=$HOME/${filename%.*}
  echo "Removing $dest"
  rm -rf $dest
done

for f in $(find . -name "*.dot_template")
do
  filename=${f#./*/}
  dest=$HOME/${filename%.*}
  echo "Removing $dest"
  rm -rf $dest
done
