alias sudo="sudo "
alias dots="cd $ZSH"
alias l="ls -lAh"
alias so="sanky-pf"
alias reload!='. ~/.zshrc'
alias selfupdate="brew update && brew upgrade && brew cleanup && rvm get stable"
alias mamp="sudo vim ~/.mamp"
alias speed="sudo find /private/var/log/asl/* -mtime +5 -exec rm -rf {} \;"
alias ios="open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app"
