alias sudo="sudo "
alias reload!='. ~/.zshrc'
alias d2u='find . -exec dos2unix {} \;'
alias slice='ssh matt@mattryan.me'
alias sanky='ssh mryan@sanky.info'
alias inacsl='ssh mryan@inacsl.org'
alias cmow='ssh mryan@citymeals.org'
alias ch='ssh mryan@covenanthouse.org'
alias dmfa='ssh mryan@dmfa.org'
alias nycafp='ssh mryan@nycafp.org'
alias gcw='ssh mryan@gildasclubwestchester.org'
alias chp='ssh mryan@supportbethisrael.org'
alias connect='ssh campaign@freedomfromhunger.org'
alias ffh='ssh ubuntu@direct.ffhdev.org'
alias share='ssh mryan@share.sanky.info'
alias mini='ssh mryan@10.10.10.150'
alias imac='ssh mryan@10.10.10.101'
alias home='ssh mryan@vnc.mrevd.me'
alias mamp="sudo vim ~/Sites/_config"
alias h5bp='git clone git://github.com/h5bp/html5-boilerplate.git h5bp && cd h5bp'
alias speed="sudo find /private/var/log/asl/* -mtime +5 -exec rm -rf {} \;"
alias ios="open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app"
alias pt="phpunit"
alias ptc="phpunit --coverage-text"
alias erd="ssh mryan@episcopalrelief.org"
alias nara="ssh dev@nara-table-contractor.secondstory.net"
